### ISSUE TITLE
Seems to be not multi-threaded or not asynchronous

### ISSUE THREAD

**Issue by ajcastro** [krakjoe/pthreads-polyfill#13]
I tried my working example of multi-threaded code, and it seems to be not multi-threaded or asynchronous. The following example should output like below:

```
Thread: 1 has started, sleeping for 2 
Thread: 2 has started, sleeping for 3 
Thread: 3 has started, sleeping for 1
Thread: 3 has finished
Thread: 1 has finished
Thread: 2 has finished
```

But when I run it using polyfill its output is not asynchronous:

```
Thread: 1 has started, sleeping for 2  // will really wait for 2 seconds, blocking thread 2 and 3
Thread: 1 has finished
Thread: 2 has started, sleeping for 3 
Thread: 2 has finished
Thread: 3 has started, sleeping for 1
Thread: 3 has finished
```

**Comment by ajcastro** [comment]
But maybe it is supposed to be like this, but what I need is the asynchronous one. But it's a bit complicated how would I setup or rebuild the php version in laravel/homestead box v0.2.6. Maybe you can help how to do that. I've been spending days to build my own php, but the problem now is that I currently haven't install mcrypt which is required in laravel 4.2.11

**Comment by ajcastro** [comment]
But maybe it is supposed to be like this, but what I need is the asynchronous one. I'm currently using laravel/homestead box v0.2.6 which has already php built-in but does not enabled pthreads. I tried to build my own php and successfully enabled pthreads, but I haven't installed mcrypt yet. As of now Im trying to install mcrypt but haven't done it yet successfully, and then I saw this "pthreads-polyfill" and I was thinking this may help me instead of building another php just to enable pthreads. 

Maybe you can help me how to to build php with pthreads enabled and also mcrypt. Im stuck on how to enable mcrypt in my custom-built php. As of now this is the instructions I followed: https://gist.github.com/ajcastro/7e0ac4003feeb7feaa12101c734006ac

**Comment by krakjoe** [comment]
That's expected :)

**Comment by putuoka** [comment]
any further explanation about this? why it's not asynchronous?

**Comment by sirsnyder** [comment]
Because this project is just a polyfill without any threading. If real asynchronity is needed, switch to https://github.com/krakjoe/pthreads.
